version: '3'
services:
  twitter:
    build: .
    environment:
      - JSON_URL
      - CONSUMER_KEY
      - CONSUMER_SECRET
      - ACCESS_TOKEN
      - ACCESS_SECRET
      - FETCH_INTERVAL
    entrypoint:
      - python
      - -u
      - ./twitter_bot.py
  telegram:
    build: .
    volumes:
      - ./storage:/storage
    environment:
      - JSON_URL
      - TELEGRAM_TOKEN
      - CHAT_ID
      - FETCH_INTERVAL
    entrypoint:
      - python
      - -u
      - ./telegram_bot.py
  pleroma :
      volumes:
        - ./storage:/storage
      build: .
      environment:
        - JSON_URL
        - PLEROMA_USERNAME
        - PLEROMA_PASSWORD
        - PLEROMA_BASE_URL
      entrypoint:
        - python
        - -u
        - ./pleroma_bot.py