version: '3'
services:
  twitter:
    build: .
    environment:
      - JSON_URL
      - CONSUMER_KEY
      - CONSUMER_SECRET
      - ACCESS_TOKEN
      - ACCESS_SECRET
      - FETCH_INTERVAL
    entrypoint:
      - python
      - -u
      - ./twitter_bot.py
  telegram:
    build: .
    volumes:
      - ./telegram-state:/storage
    environment:
      - JSON_URL
      - TELEGRAM_TOKEN
      - CHAT_ID
      - FETCH_INTERVAL
    entrypoint:
      - python
      - -u
      - ./telegram_bot.py